[package]
name = "avc_asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
num-traits = "0.2"
num-derive = "0.2"
termion = "1.5.6"
